export const SCHEMA_VERSION = 1;
export const PRODUCT_ID = "storybook";
export const PROJECT_ID_PATTERN = /^[a-z0-9][a-z0-9-]{2,63}$/;
export const SUPPORTED_THEME_IDS = new Set(["spiderman"]);
export const MODULE_TYPES = ["reasons", "gallery", "music", "letter"];
export const OCCASION_IDS = new Set(["romantic", "anniversary", "birthday", "appreciation", "friendship", "graduation", "just-because"]);
export const MAX_REASONS = 10;
export const MAX_GALLERY_ITEMS = 15;
export const MAX_MUSIC_TRACKS = 3;
const DEFAULTS = {
  id: { titles: { reasons: "Kenapa Kamu Berarti", gallery: "Arsip Kenangan", music: "Soundtrack Kita", letter: "Sebuah Surat" }, subtitles: { reasons: "Hal-hal kecil yang membuatmu istimewa.", gallery: "Momen yang ingin selalu disimpan.", music: "Lagu-lagu yang membawa kita kembali.", letter: "Kata-kata yang ingin kusampaikan." }, finale: ["Satu hal terakhir untukmu", "Terima kasih sudah menjadi bagian dari cerita yang begitu berarti.", "Dengan penuh kasih,"] },
  en: { titles: { reasons: "Why You Matter", gallery: "Memory Archive", music: "Our Soundtrack", letter: "A Letter" }, subtitles: { reasons: "The little things that make you special.", gallery: "Moments worth keeping forever.", music: "Songs that bring us back.", letter: "Words I have been meaning to say." }, finale: ["One last thing for you", "Thank you for being part of a story that means so much.", "With all my love,"] }
};
const PRESETS = {
  romantic: { id: ["Sebuah cerita kecil untukmu", "Untuk seseorang yang membuat segalanya terasa lebih indah", "Ada beberapa hal yang ingin kusimpan dan kusampaikan khusus untukmu."], en: ["A little story for you", "For the one who makes everything feel brighter", "There are a few memories and words I saved especially for you."] },
  anniversary: { id: ["Merayakan cerita kita", "Satu perjalanan, begitu banyak kenangan", "Mari melihat kembali hal-hal kecil yang membuat perjalanan ini berarti."], en: ["Celebrating our story", "One journey, so many memories", "Let us revisit the little things that made this journey meaningful."] },
  birthday: { id: ["Hari spesialmu", "Selamat ulang tahun, bintang utama hari ini", "Ada empat kejutan kecil yang dibuat khusus untuk merayakanmu."], en: ["Your special day", "Happy birthday to today’s brightest star", "Four little surprises are waiting here to celebrate you."] },
  appreciation: { id: ["Karena kamu pantas mendengarnya", "Terima kasih sudah menjadi dirimu", "Halaman kecil ini menyimpan alasan kenapa kehadiranmu begitu berarti."], en: ["Because you deserve to hear it", "Thank you for being exactly who you are", "These pages hold a few reasons why your presence means so much."] },
  friendship: { id: ["Untuk partner segala cerita", "Hidup jauh lebih seru karena ada kamu", "Untuk semua tawa, kekacauan, dan kenangan yang kita kumpulkan."], en: ["For my favorite partner in everything", "Life is much more fun with you in it", "For every laugh, little chaos, and memory we collected together."] },
  graduation: { id: ["Satu bab selesai", "Lihat sejauh apa kamu sudah melangkah", "Ini adalah perayaan untuk kerja keras, keberanian, dan perjalanan barumu."], en: ["One chapter complete", "Look how far you have come", "A celebration of your hard work, courage, and the journey ahead."] },
  "just-because": { id: ["Tidak perlu menunggu hari spesial", "Ini dibuat hanya karena aku memikirkanmu", "Kadang hal yang paling tulus datang tanpa alasan selain rasa sayang."], en: ["No special date required", "I made this simply because you crossed my mind", "Sometimes the sweetest things need no reason beyond caring."] }
};
const SAMPLE_REASONS = {
  id: ["Kamu membuat hari biasa terasa istimewa.", "Kamu selalu mendengarkan dengan sepenuh hati.", "Senyummu membuat segalanya terasa lebih ringan.", "Kamu selalu tahu cara membuatku tertawa."],
  en: ["You make ordinary days feel special.", "You listen with your whole heart.", "Your smile makes everything lighter.", "You always know how to make me laugh."]
};
function clean(value, fallback = "", max = 10000) { return typeof value === "string" ? value.trim().slice(0, max) : fallback; }
function media(value) { const url = clean(value, "", 2048); return url.startsWith("/assets/") || /^https:\/\//i.test(url) ? url : ""; }
export function normalizeThemeId(value) { const id = clean(value, "spiderman", 40).toLowerCase(); return SUPPORTED_THEME_IDS.has(id) ? id : "spiderman"; }
function language(value) { return value === "en" ? "en" : "id"; }
function occasion(value) { return OCCASION_IDS.has(value) ? value : "romantic"; }
function modules(value, locale) { const source = Array.isArray(value) ? value : []; return MODULE_TYPES.map((type, index) => { const item = source.find(entry => entry?.type === type) || {}; return { type, enabled: item.enabled !== false, order: Number.isFinite(Number(item.order)) ? Number(item.order) : index, title: clean(item.title, DEFAULTS[locale].titles[type], 80), subtitle: clean(item.subtitle, DEFAULTS[locale].subtitles[type], 160) }; }).sort((a, b) => a.order - b.order).map((item, order) => ({ ...item, order })); }
export function emptyProject(projectId) { const locale = "id", opening = PRESETS.romantic.id; return { schemaVersion: SCHEMA_VERSION, productId: PRODUCT_ID, projectId, status: "draft", themeId: "spiderman", occasionPreset: "romantic", identity: { recipient: "", sender: "", eventDate: "" }, opening: { eyebrow: opening[0], title: opening[1], message: opening[2] }, modules: modules([], locale), reasons: { items: [...SAMPLE_REASONS.id] }, gallery: { items: [{ id: "media-1", mediaType: "image", mediaUrl: "", title: "", caption: "" }] }, music: { tracks: [] }, letter: { greeting: "", paragraphs: [], signoff: "" }, finale: { title: DEFAULTS.id.finale[0], message: DEFAULTS.id.finale[1], signoff: DEFAULTS.id.finale[2] }, settings: { language: locale }, createdAt: "", updatedAt: "", publishedAt: null }; }
export function normalizeProject(input, projectId, existing = null) {
  const source = input && typeof input === "object" ? input : {}; const previous = existing && typeof existing === "object" ? existing : emptyProject(projectId); const locale = language(source.settings?.language ?? previous.settings?.language); const fallback = emptyProject(projectId); const preset = occasion(source.occasionPreset); const opening = PRESETS[preset][locale]; const gallerySource = Array.isArray(source.gallery?.items) ? source.gallery.items : []; const trackSource = Array.isArray(source.music?.tracks) ? source.music.tracks : [];
  return { schemaVersion: SCHEMA_VERSION, productId: PRODUCT_ID, projectId, status: source.status === "published" ? "published" : source.status === "archived" ? "archived" : "draft", themeId: normalizeThemeId(source.themeId), occasionPreset: preset,
    identity: { recipient: clean(source.identity?.recipient, "", 80), sender: clean(source.identity?.sender, "", 80), eventDate: clean(source.identity?.eventDate, "", 40) }, opening: { eyebrow: clean(source.opening?.eyebrow, opening[0], 100), title: clean(source.opening?.title, opening[1], 180), message: clean(source.opening?.message, opening[2], 400) }, modules: modules(source.modules, locale),
    reasons: { items: (Array.isArray(source.reasons?.items) ? source.reasons.items : []).slice(0, MAX_REASONS).map(value => clean(value, "", 220)).filter(Boolean) },
    gallery: { items: gallerySource.slice(0, MAX_GALLERY_ITEMS).map((item, index) => { const mediaType = item?.mediaType === "video" ? "video" : "image"; return { id: clean(item?.id, `media-${index + 1}`, 100), mediaType, mediaUrl: media(item?.mediaUrl || item?.imageUrl || item?.videoUrl), title: clean(item?.title, "", 100), caption: clean(item?.caption || item?.story, "", 350) }; }) },
    music: { tracks: trackSource.slice(0, MAX_MUSIC_TRACKS).map((track, index) => ({ id: clean(track?.id, `track-${index + 1}`, 100), sourceType: track?.sourceType === "upload" ? "upload" : "catalog", catalogId: clean(track?.catalogId, "", 100), audioUrl: media(track?.audioUrl), coverUrl: media(track?.coverUrl), title: clean(track?.title, "", 100), artist: clean(track?.artist, "", 100) })).filter(track => track.audioUrl || track.title) },
    letter: { greeting: clean(source.letter?.greeting, "", 120), paragraphs: (Array.isArray(source.letter?.paragraphs) ? source.letter.paragraphs : []).slice(0, 50).map(value => clean(value, "", 4000)).filter(Boolean), signoff: clean(source.letter?.signoff, "", 220) },
    finale: { title: clean(source.finale?.title, DEFAULTS[locale].finale[0], 140), message: clean(source.finale?.message, DEFAULTS[locale].finale[1], 500), signoff: clean(source.finale?.signoff, DEFAULTS[locale].finale[2], 160) }, settings: { language: locale }, createdAt: previous.createdAt || clean(source.createdAt, "", 40), updatedAt: clean(source.updatedAt || previous.updatedAt, "", 40), publishedAt: source.publishedAt || previous.publishedAt || null };
}
export function validatePublishedProject(project) { const errors = {}; const enabled = project.modules.filter(item => item.enabled); if (!PROJECT_ID_PATTERN.test(project.projectId)) errors.projectId = "Project ID tidak valid."; if (project.identity.recipient.length < 2) errors.recipient = "Nama penerima wajib diisi."; if (project.identity.sender.length < 2) errors.sender = "Nama pengirim wajib diisi."; if (enabled.length < 2) errors.modules = "Aktifkan setidaknya dua bagian gift."; if (enabled.some(item => item.type === "reasons") && project.reasons.items.length < 4) errors.reasons = "Isi minimal empat alasan."; if (enabled.some(item => item.type === "gallery") && !project.gallery.items.some(item => item.mediaUrl)) errors.gallery = "Tambahkan setidaknya satu foto atau video."; if (enabled.some(item => item.type === "music") && (!project.music.tracks.length || project.music.tracks.some(item => !item.audioUrl || !item.title))) errors.music = "Setiap lagu membutuhkan file dan judul."; if (enabled.some(item => item.type === "letter") && (!project.letter.greeting || !project.letter.paragraphs.length || !project.letter.signoff)) errors.letter = "Lengkapi surat."; return errors; }
export function publicProject(record) { const project = normalizeProject(record, record.projectId, record); delete project.auth; return project; }
