(function (root) {
  "use strict";
  const messages = {
    id: {
      "common.back": "Kembali", "common.close": "Tutup", "common.next": "Lanjut", "common.previous": "Sebelumnya", "common.save": "Simpan", "common.delete": "Hapus", "common.add": "Tambah", "common.loading": "Memuat...", "common.retry": "Coba Lagi",
      "gift.tap": "Ketuk untuk membuka", "gift.for": "Dibuat khusus untuk", "gift.from": "dari", "gift.menuEyebrow": "BAGIAN CERITA", "gift.menuTitle": "Pilih halaman yang ingin kamu buka", "gift.open": "Buka bagian", "gift.completed": "Sudah dibuka", "gift.finish": "Buka penutup", "gift.replay": "Putar ulang cerita", "gift.empty": "Bagian ini belum memiliki isi.", "gift.galleryPrev": "Media sebelumnya", "gift.galleryNext": "Media berikutnya", "gift.play": "Putar", "gift.pause": "Jeda", "gift.fullLetter": "Tampilkan seluruh surat",
      "studio.title": "Storybook Studio", "studio.subtitle": "Buat cerita interaktif yang personal dalam sembilan langkah.", "studio.theme": "Tema & Momen", "studio.opening": "Opening", "studio.reasons": "Why You Matter", "studio.gallery": "Memory Archive", "studio.atlas": "The Map Of Perfect Tiny Thing", "studio.music": "Our Soundtrack", "studio.letter": "A Letter", "studio.arrange": "Susun & Finale", "studio.publish": "Preview & Publish", "studio.language": "Bahasa", "studio.recipient": "Nama penerima", "studio.sender": "Nama pengirim", "studio.date": "Tanggal spesial (opsional)", "studio.occasion": "Preset momen", "studio.presetWarning": "Mengganti preset akan mengganti teks opening. Lanjutkan?", "studio.themeHelp": "Tema hanya mengubah tampilan. Semua tulisan dan media tetap sama.", "studio.autosaved": "Tersimpan otomatis", "studio.saving": "Menyimpan...", "studio.unsaved": "Ada perubahan", "studio.publishButton": "Publish Gift", "studio.published": "Gift sudah live", "studio.preview": "Live Preview", "studio.enable": "Aktifkan bagian", "studio.minimum": "Aktifkan minimal dua bagian.", "studio.order": "Urutan bagian", "studio.finalTitle": "Judul penutup", "studio.finalMessage": "Pesan penutup", "studio.finalSignoff": "Kalimat penutup", "studio.copy": "Salin Link", "studio.openGift": "Buka Gift",
      "studio.openingHelp": "Atur greeting dan empat foto yang muncul saat kado dibuka.", "studio.openingPhotos": "Empat foto opening", "studio.openingPhotosHelp": "Foto mempertahankan rasio asli dan tampil memenuhi panel.", "studio.choosePhoto": "Pilih foto", "studio.removePhoto": "Hapus foto", "studio.reasonsHelp": "Isi 4–10 alasan personal. Urutkan sesuai alur yang kamu inginkan.", "studio.galleryHelp": "Maksimal 15 foto/video. Foto otomatis dicrop 4:3 dan dikonversi ke WebP.", "studio.atlasHelp": "Tambahkan hingga 10 tempat penting. Cukup paste koordinat atau link Google Maps, kami akan membaca titiknya otomatis.", "studio.atlasShortHelp": "Tips: paste seperti -6.2000, 106.8000 atau link lengkap Google Maps dari browser. Link pendek maps.app.goo.gl tidak bisa dibaca.", "studio.addLocation": "+ Tambah lokasi", "studio.locationName": "Nama tempat", "studio.locationInput": "Lokasi di Google Maps atau koordinat", "studio.locationPlaceholder": "Paste -6.2000, 106.8000 atau link Google Maps", "studio.locationEmpty": "Paste koordinat atau link Google Maps.", "studio.locationReady": "Titik lokasi siap", "studio.locationInvalid": "Titik belum ditemukan. Coba paste koordinat atau link Google Maps lengkap dari browser.", "studio.locationShortLink": "Link pendek tidak bisa dibaca. Paste koordinat atau link Google Maps lengkap dari browser.", "studio.locationPhoto": "Foto lokasi (opsional)", "studio.locationNote": "Cerita singkat (opsional)", "studio.musicHelp": "Pilih dari katalog atau upload MP3 sendiri. Maksimal tiga lagu.", "studio.letterHelp": "Tulis surat panjang. Pisahkan paragraf dengan satu baris kosong.", "studio.previewHelp": "Preview memakai renderer yang sama dengan public gift.", "studio.publishHint": "Publish untuk mengaktifkan public gift link.", "studio.addReason": "+ Tambah alasan", "studio.addMedia": "+ Tambah media", "studio.searchCatalog": "Cari katalog", "studio.searchPlaceholder": "Cari judul atau artis...", "studio.uploadMp3": "Upload MP3", "studio.chooseMedia": "Pilih foto/video", "studio.reason": "Alasan", "studio.titleField": "Judul", "studio.caption": "Caption", "studio.artist": "Artis", "studio.body": "Isi surat", "studio.signoff": "Signoff", "studio.greeting": "Greeting", "studio.eyebrow": "Eyebrow", "studio.headline": "Headline", "studio.intro": "Pesan pembuka", "studio.publishing": "Mempublikasikan...", "studio.maxImage": "Foto maksimal 8 MB.", "studio.maxVideo": "Video maksimal 20 MB.", "studio.maxAudio": "Audio maksimal 20 MB.", "studio.maxTracks": "Maksimal tiga lagu.",
      "admin.title": "Storybook Control Room", "admin.generate": "Generate Studio Link", "admin.search": "Cari penerima, pengirim, project, preset, atau tema...", "admin.total": "Total", "admin.draft": "Draft", "admin.published": "Published", "admin.archived": "Archived"
    },
    en: {
      "common.back": "Back", "common.close": "Close", "common.next": "Next", "common.previous": "Previous", "common.save": "Save", "common.delete": "Delete", "common.add": "Add", "common.loading": "Loading...", "common.retry": "Try Again",
      "gift.tap": "Tap to open", "gift.for": "Made especially for", "gift.from": "from", "gift.menuEyebrow": "STORY CHAPTERS", "gift.menuTitle": "Choose a page to open", "gift.open": "Open section", "gift.completed": "Opened", "gift.finish": "Open the finale", "gift.replay": "Replay the story", "gift.empty": "This section does not have content yet.", "gift.galleryPrev": "Previous media", "gift.galleryNext": "Next media", "gift.play": "Play", "gift.pause": "Pause", "gift.fullLetter": "Show the full letter",
      "studio.title": "Storybook Studio", "studio.subtitle": "Create a personal interactive story in nine steps.", "studio.theme": "Theme & Occasion", "studio.opening": "Opening", "studio.reasons": "Why You Matter", "studio.gallery": "Memory Archive", "studio.atlas": "The Map Of Perfect Tiny Thing", "studio.music": "Our Soundtrack", "studio.letter": "A Letter", "studio.arrange": "Arrange & Finale", "studio.publish": "Preview & Publish", "studio.language": "Language", "studio.recipient": "Recipient name", "studio.sender": "Sender name", "studio.date": "Special date (optional)", "studio.occasion": "Occasion preset", "studio.presetWarning": "Changing the preset will replace the opening copy. Continue?", "studio.themeHelp": "Themes only change the look. Your writing and media stay the same.", "studio.autosaved": "Saved automatically", "studio.saving": "Saving...", "studio.unsaved": "Unsaved changes", "studio.publishButton": "Publish Gift", "studio.published": "Gift is live", "studio.preview": "Live Preview", "studio.enable": "Enable section", "studio.minimum": "Enable at least two sections.", "studio.order": "Section order", "studio.finalTitle": "Finale title", "studio.finalMessage": "Finale message", "studio.finalSignoff": "Finale signoff", "studio.copy": "Copy Link", "studio.openGift": "Open Gift",
      "studio.openingHelp": "Set the greeting and four photos shown while the gift opens.", "studio.openingPhotos": "Four opening photos", "studio.openingPhotosHelp": "Photos keep their original ratio and fill each panel.", "studio.choosePhoto": "Choose photo", "studio.removePhoto": "Remove photo", "studio.reasonsHelp": "Write 4–10 personal reasons and arrange them in your preferred order.", "studio.galleryHelp": "Up to 15 photos or videos. Photos are center-cropped to 4:3 and converted to WebP.", "studio.atlasHelp": "Add up to 10 meaningful places. Paste coordinates or a Google Maps link and we will read the point automatically.", "studio.atlasShortHelp": "Tip: paste -6.2000, 106.8000 or a full Google Maps link from a browser. Short maps.app.goo.gl links cannot be read.", "studio.addLocation": "+ Add location", "studio.locationName": "Place name", "studio.locationInput": "Google Maps location or coordinates", "studio.locationPlaceholder": "Paste -6.2000, 106.8000 or a Google Maps link", "studio.locationEmpty": "Paste coordinates or a Google Maps link.", "studio.locationReady": "Location is ready", "studio.locationInvalid": "We could not find that point. Paste coordinates or a full Google Maps link from a browser.", "studio.locationShortLink": "Short links cannot be read. Paste coordinates or a full Google Maps link from a browser.", "studio.locationPhoto": "Location photo (optional)", "studio.locationNote": "Short story (optional)", "studio.musicHelp": "Choose from the catalog or upload an MP3. Up to three songs.", "studio.letterHelp": "Write a longer letter. Separate paragraphs with one blank line.", "studio.previewHelp": "The preview uses the same renderer as the public gift.", "studio.publishHint": "Publish to activate the public gift link.", "studio.addReason": "+ Add reason", "studio.addMedia": "+ Add media", "studio.searchCatalog": "Search catalog", "studio.searchPlaceholder": "Search title or artist...", "studio.uploadMp3": "Upload MP3", "studio.chooseMedia": "Choose photo/video", "studio.reason": "Reason", "studio.titleField": "Title", "studio.caption": "Caption", "studio.artist": "Artist", "studio.body": "Letter body", "studio.signoff": "Signoff", "studio.greeting": "Greeting", "studio.eyebrow": "Eyebrow", "studio.headline": "Headline", "studio.intro": "Intro message", "studio.publishing": "Publishing...", "studio.maxImage": "Photos must be 8 MB or smaller.", "studio.maxVideo": "Videos must be 20 MB or smaller.", "studio.maxAudio": "Audio must be 20 MB or smaller.", "studio.maxTracks": "You can add up to three songs.",
      "admin.title": "Storybook Control Room", "admin.generate": "Generate Studio Link", "admin.search": "Search recipient, sender, project, preset, or theme...", "admin.total": "Total", "admin.draft": "Draft", "admin.published": "Published", "admin.archived": "Archived"
    }
  };
  let locale = "id";
  function normalize(value) { return value === "en" ? "en" : "id"; }
  function setLocale(value) { locale = normalize(value); document.documentElement.lang = locale; return locale; }
  function t(key, vars = {}, selected = locale) { let value = messages[normalize(selected)]?.[key] || messages.id[key] || key; Object.entries(vars).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); }); return value; }
  function apply(scope = document) {
    scope.querySelectorAll("[data-i18n]").forEach(node => { node.textContent = t(node.dataset.i18n); });
    scope.querySelectorAll("[data-i18n-placeholder]").forEach(node => { node.placeholder = t(node.dataset.i18nPlaceholder); });
    scope.querySelectorAll("[data-i18n-aria-label]").forEach(node => { node.setAttribute("aria-label", t(node.dataset.i18nAriaLabel)); });
  }
  const api = { messages, get locale() { return locale; }, normalize, setLocale, t, apply };
  if (typeof module === "object" && module.exports) module.exports = api;
  root.StorybookI18n = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
