name = "storybook-gift-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://storybook.for-you-always.my.id"
ALLOWED_ORIGIN_SUFFIXES = ".for-you-always.my.id"
PUBLIC_GIFT_BASE_URL = "https://storybook.for-you-always.my.id"
PUBLIC_STUDIO_BASE_URL = "https://storybook.for-you-always.my.id"
MEDIA_BASE_URL = "https://cdn.for-you-always.my.id"

# Create a new KV namespace before deployment and replace this placeholder.
[[kv_namespaces]]
binding = "GIFT_KV"
id = "a94948f0916b4dc89cdb7369ce2f3fff"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "valentine-upload"
